### ISSUE TITLE
You may need these libraries!

### ISSUE THREAD

**Issue by cyanial** [Allenxuxu/Xmqtt#1]
I know that a mqtt broker may depend on the following C/C++ libraries:
(based on my experience of cross compiling the mosquitto)

1. openssl (https://github.com/openssl/openssl)
2. c-ares (https://github.com/c-ares/c-ares)
3. e2fsprogs (https://github.com/tytso/e2fsprogs) for the uuid lib and some other tools or utilties.

**Comment by Allenxuxu** [comment]
Thank you
I will continue to finish it.
